### ISSUE TITLE
Podman Desktop 1.8.0 is broken since updating to Podman 5.0.0 via winget

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#516]
Cannot recreate podman machines

```
Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: unable to load machine config file: "json: cannot unmarshal string into Go struct field MachineConfig.ImagePath of type define.VMFile"
```

https://github.com/containers/podman/issues/22144
https://github.com/microsoft/winget-pkgs/pull/145266

**Comment by kachick** [comment]
uninstall and re-install didn't fix 🤔

**Comment by kachick** [comment]
Similar https://github.com/containers/podman-desktop/issues/6495

**Comment by kachick** [comment]
Same error even after `wsl --unregister podman-machine-default`

**Comment by kachick** [comment]
https://github.com/containers/podman/issues/22144#issuecomment-2016343780

```pwsh
cd ${Env:USERPROFILE}\.config\containers\podman\machine\wsl\

Remove-Item .\podman-machine-*
```

After this, I can create podman-machine

**Comment by alisonatwork** [comment]
Was it sufficient to delete the machines using WSL and then just remove the matching JSON files from .config, or was there some other dangling data that needed to be cleaned?

**Comment by kachick** [comment]
For now and for me, removing the json and lock file looks like the crucial part. Now it seems to work. 

But first I uninstalled podman, podman desktop and podman-machine.  I don't know which step I could skip 🤔.

**Comment by kachick** [comment]
Your research and report https://github.com/containers/podman/issues/22144#issuecomment-2016343780 helped me a lot, thank you!

**Comment by xaocon** [comment]
> Was it sufficient to delete the machines using WSL and then just remove the matching JSON files from .config, or was there some other dangling data that needed to be cleaned?

I ran into the same problem and deleting the config files and wsl machine was enough. I did it while podman desktop was not running if that helps any.
