### ISSUE TITLE
Tiling window manager for Windows

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#529]
Windows part of https://github.com/kachick/dotfiles/issues/528

- https://github.com/LGUG2Z/komorebi
- Windows default feature

**Comment by kachick** [comment]
FancyZones is helpful, but it does not save the layout and no auto fitting

**Comment by phanirithvij** [comment]
Hi there is glazewm, I found it from this article https://christitus.com/glazewm-tiling-window-management/ (youtube vid).
It's been a while since my windows 10 install got corrupted and I moved to nixos so I haven't had the chance to try it.

**Comment by kachick** [comment]
Thank you for sharing it with me. 🙏  I'll try it while struggling to use the Windows OS!
