### ISSUE TITLE
How about introducing tailscale?

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#573]
https://tailscale.com/

https://github.com/kachick/dotfiles/pull/568
https://github.com/kachick/times_kachick/issues/286

**Comment by phanirithvij** [comment]
Just some thoughts on headscale.

Do you have a dedicated vps with very high uptime? If not, then tailscale is far more convinient compared to headscale.

I've hosted headscale for a while (not with nix but via docker) on a vps but when I switched to tailscale with github login, it was too convinient, so until tailscale the company does something anti-consumer I don't mind using it directly.

But it is a good idea to have a headscale config ready to go to switch, in case what I said does happen.

you may find this useful https://github.com/gurucomputing/headscale-ui

**Comment by kachick** [comment]
Thank you for sharing it! I like hearing actual experiences and feelings from users. The headscale report helps a lot.

I will check the tools when I explore the introducing headscale.

https://github.com/kachick/dotfiles/blob/436ec1401fd9f73edfb9773e4e4a513b75e7a8b5/nixos/desktop/default.nix#L314
