### ISSUE TITLE
nightly(flake) wezterm on wayland is broken again

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#679]
Looks like appeared since https://github.com/kachick/dotfiles/pull/676

https://github.com/wez/wezterm/issues/5604
https://github.com/wez/wezterm/issues/5103

Run, but disable IME

```lua
  config.enable_wayland = false
  config.use_ime = true
```

Don't run

```lua
  config.enable_wayland = true
  config.use_ime = true
```

**Comment by kachick** [comment]
>Looks like appeared since https://github.com/kachick/dotfiles/pull/676

Or more before... :thinking:

**Comment by Yappaholic** [comment]
> Don't run
> 
> ```lua
>   config.enable_wayland = true
>   config.use_ime = true
> ```

I have no trouble running ime with wayland, did you install nightly wezterm like this?
https://github.com/wez/wezterm/pull/3547#issuecomment-1915820504

**Comment by kachick** [comment]
Yes, at least I wish I'm going on that method... 😅

https://github.com/kachick/dotfiles/blob/a31b2c05edf13a8d99fe61d5ae1b11b0cb6f985e/flake.nix#L18-L19
https://github.com/kachick/dotfiles/blob/a31b2c05edf13a8d99fe61d5ae1b11b0cb6f985e/nixos/configuration.nix#L209-L210

**Comment by kachick** [comment]
Are you using same wezterm ref as me? https://github.com/kachick/dotfiles/blob/a31b2c05edf13a8d99fe61d5ae1b11b0cb6f985e/flake.lock#L660-L661

**Comment by Yappaholic** [comment]
> Are you using same wezterm ref as me?

No, mine is this
``` json
"repo": "wezterm",
"rev": "69686f4564ea460111936dee3179ecf8c80e9930",
```

**Comment by Yappaholic** [comment]
I've updated flake and compiling now, should probably take 2 years, I'll update if it breaks ime for me

**Comment by kachick** [comment]
https://github.com/wez/wezterm/commit/69686f4564ea460111936dee3179ecf8c80e9930

Thanks for sharing. 
That is a version from 2 weeks ago, even though it's a nightly version. (I don't know why wezterm does not release stable version in this 5 months...)

**Comment by kachick** [comment]
I may have to stop updating wezterm flake instead of the current cycle and auto-merging 🤔

**Comment by Yappaholic** [comment]
> I don't know why wezterm does not release stable version in this 5 months

Probably because there isn't one(or that's what I assume).
It depends if it's bad or good, but not having updated and fixed version in nixpkgs can give some new nix users headaches

**Comment by Yappaholic** [comment]
> I may have to stop updating wezterm flake instead of the current cycle and auto-merging 🤔

It could be and option to make it a flake module for home-manager or system flake and just update it individually whenever you feel like it. Or you can go to 15 min home builds every time you update everything(at least it's that bad for me)

**Comment by kachick** [comment]
Yes... I'm also tracking https://github.com/NixOS/nixpkgs/pull/314871 for a nixpkgs side solution

**Comment by Yappaholic** [comment]
So, everything compiled and I still don't have an error
Here's the rev:
```json
"repo": "wezterm",
"rev": "c9116830c27baf0c547a1524d33363fd5e42295a",

```
Wayland and IME both enabled, so can't tell much. The fault can also be on the compositor side, I'm on Hyprland 0.42

My suggestion is that you try to update flakes and recompile and/or search for any IME caveats in your compositor of choice

> Yes... I'm also tracking [NixOS/nixpkgs#314871](https://github.com/NixOS/nixpkgs/pull/314871) for a nixpkgs side solution

I think for now it's not worth it and you should stick with the flake because even on unstable updating nixpkgs can take some time, that's why I almost stopped using wezterm altogether until found out about flake

**Comment by kachick** [comment]
Updated in https://github.com/kachick/dotfiles/pull/683, but the behavior looks not changed
I don't know how to dig into KDE logs, but got some wezterm error logs here

```console
> wezterm --config 'enable_wayland=true'
12:15:29.957  ERROR  env_bootstrap > panic at window/src/os/wayland/connection.rs:207:51 - called `Option::unwrap()` on a `None` value
   0: env_bootstrap::register_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic
   7: core::option::unwrap_failed
   8: <window::os::wayland::connection::WaylandConnection as window::connection::ConnectionOps>::screens
   9: <window::os::x_and_wayland::Connection as window::connection::ConnectionOps>::screens
  10: mlua::lua::Lua::create_function::{{closure}}
  11: mlua::lua::Lua::create_callback::call_callback
  12: luaD_precall
  13: luaV_execute
  14: luaD_rawrunprotected
  15: lua_resume
  16: <mlua::thread::AsyncThread<R> as core::future::future::Future>::poll
  17: config::lua::emit_event::{{closure}}
  18: wezterm_gui::async_run_terminal_gui::{{closure}}
  19: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll
  20: async_task::raw::RawTask<F,T,S,M>::run
  21: window::spawn::SpawnQueue::run
  22: <window::os::wayland::connection::WaylandConnection as window::connection::ConnectionOps>::run_message_loop
  23: wezterm_gui::run_terminal_gui
  24: wezterm_gui::main
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: std::rt::lang_start::{{closure}}
  27: std::rt::lang_start_internal
  28: main
  29: __libc_start_call_main
  30: __libc_start_main@@GLIBC_2.34
  31: _start

thread 'main' panicked at window/src/os/wayland/connection.rs:207:51:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

https://github.com/wez/wezterm/blob/c9116830c27baf0c547a1524d33363fd5e42295a/window/src/connection.rs#L57

These threads looks not completely related

https://github.com/wez/wezterm/issues/5518#issuecomment-2227123986
https://github.com/wez/wezterm/issues/3050
https://github.com/wez/wezterm/issues/2559

**Comment by kachick** [comment]
https://github.com/wez/wezterm/pull/4777#issuecomment-2014478175

```bash
env WAYLAND_DISPLAY=1 wezterm --config 'enable_wayland=true'
```

Looks fixed :joy:

**Comment by kachick** [comment]
https://github.com/wez/wezterm/blob/c9116830c27baf0c547a1524d33363fd5e42295a/wezterm-client/src/discovery.rs#L276-L287 :eyes:
