### ISSUE TITLE
How about adding AI based solutions to maintain this repository?

### ISSUE THREAD

**Issue by kachick** [kachick/dotfiles#703]
* SWE-agent: https://github.com/princeton-nlp/SWE-agent/issues/23
* A good experience with CodeRabbit: https://github.com/pankona/pankona.github.com/pull/228#discussion_r1475470927
* Bad experiences with CodeRabbit:
  * https://github.com/pankona/pankona.github.com/issues/204#issuecomment-1945368019
  * https://github.com/pankona/pankona.github.com/pull/304#discussion_r1733201252
  * https://github.com/pankona/pankona.github.com/pull/311#discussion_r1758782105
* Neutral experience for Copilot https://github.com/kachick/dotfiles/pull/443#issuecomment-1983234729

**Comment by mistycaseyward12** [comment]
Thump her and be bam bam

**Comment by kachick** [comment]
![image](https://github.com/user-attachments/assets/7beb0974-5823-4a69-a8a4-444121781024)

CodeRabbit looks like provided for response code checker 🙄

**Comment by kachick** [comment]
It is helpful to get boilerplate faster, however I couldn't get any good experience around dotfiles yet...

**Comment by kachick** [comment]
GitHub introduced beta feature...

![image](https://github.com/user-attachments/assets/5cbde2bf-5a54-4f42-a796-5abe61934072)


https://github.com/orgs/community/discussions/139872

![image](https://github.com/user-attachments/assets/617fcfe9-168e-449c-9c4d-24266d8a1f80)

![image](https://github.com/user-attachments/assets/67533b85-4363-4ca4-ab78-fc0e19f7ba03)

Looks not useful for now... 😢

**Comment by kachick** [comment]
![image](https://github.com/user-attachments/assets/8a9a89e6-4662-431c-b8dc-d48e485b8550)

![image](https://github.com/user-attachments/assets/8dbbaf86-63a7-4935-86c8-68088f5fec31)

![image](https://github.com/user-attachments/assets/07941c5c-ec6a-4a83-9dda-bfb6444ef909)

![image](https://github.com/user-attachments/assets/65c623b9-7dd3-4390-880a-570dc9512866)

🤷‍♂️

**Comment by kachick** [comment]
Cline family has a bunch of good ratings and reviews. 🤔

**Comment by kachick** [comment]
![Image](https://github.com/user-attachments/assets/2c6916db-9527-45c6-bb61-06e0822faf0e)

😮 

https://docs.github.com/en/copilot/using-github-copilot/code-review/using-copilot-code-review

**Comment by kachick** [comment]
Installed gemini-cli in local. https://github.com/kachick/dotfiles/commit/3ce3b3c0a4e0d796e952040cb2b91adaa05e4dc9
